### ISSUE TITLE
批量导入

### ISSUE THREAD

**Issue by chanson-chan** [dromara/orion-visor#14]
兄弟, 考虑加个批量导入机器的功能吗, 一个个加太麻烦

**Comment by lijiahangmax** [comment]
未来有时间会加的

**Comment by Faker523** [comment]
您好，请问下批量导入这个功能后续有计划添加吗？确实蛮实用的，几千台虚拟机一台一台导入不太方便

**Comment by lijiahangmax** [comment]
后面会加, 但是现在没时间加, 现在最简单的方式是直接编辑数据库
