### ISSUE TITLE
ip记录伪造

### ISSUE THREAD

**Issue by te5tb99** [dromara/orion-visor#25]
<img width="1067" alt="image" src="https://github.com/dromara/orion-visor/assets/48084662/087bda12-4f9b-4f8c-bf9a-00e5272b7e89">

**Comment by lijiahangmax** [comment]
如果是本地请求调试 或内网ip会显示这个  请问你是怎么操作的呢 可以复现吗在 2024年6月14日，上午11:00，01dGu0 ***@***.***> 写道：﻿
image.png (view on web)

**Comment by te5tb99** [comment]
<img width="1058" alt="image" src="https://github.com/dromara/orion-visor/assets/48084662/a5318791-b8ba-40b7-8d27-ed281a0ee126">
<img width="914" alt="image" src="https://github.com/dromara/orion-visor/assets/48084662/f51c2837-3806-4c2a-af4c-644a6f1135a9">

**Comment by te5tb99** [comment]
<img width="1058" alt="image" src="https://github.com/dromara/orion-visor/assets/48084662/a5318791-b8ba-40b7-8d27-ed281a0ee126">
<img width="914" alt="image" src="https://github.com/dromara/orion-visor/assets/48084662/f51c2837-3806-4c2a-af4c-644a6f1135a9">

**Comment by lijiahangmax** [comment]
好的 下个版本改为 X-Real-IP
