### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by lwxpan** [dromara/orion-visor#26]
![1718549853937](https://github.com/dromara/orion-visor/assets/145948311/812e1d6d-3d41-44a9-bfc8-c451fa07056a)
安装后登录后台 提示Request failed with status code 502

**Comment by lijiahangmax** [comment]
这个原因是后端还没起来 nginx 已经起来了 等待2分钟就好了在 2024年6月16日，下午10:59，lwxpan ***@***.***> 写道：﻿
1718549853937.jpg (view on web)
安装后登录后台 提示Request failed with status code 502
