### ISSUE TITLE
请问，是否需要帮忙实现接口 e2e 测试

### ISSUE THREAD

**Issue by LinuxSuRen** [dromara/orion-visor#27]
我已经帮助如下的一些项目实现了 e2e 接口测试，如果您希望能 e2e 的话，我愿意帮忙实现。期待收到回复。

https://github.com/LinuxSuRen/api-testing/discussions/284

**Comment by lijiahangmax** [comment]
可以的  欢迎PR

**Comment by lijiahangmax** [comment]
https://github.com/dromara/orion-visor/actions/runs/9691961663/job/26744389464

可以帮忙看下这个问题吗

**Comment by LinuxSuRen** [comment]
现在是不是会从 cookie 里获取认证信息呢

**Comment by lijiahangmax** [comment]
不会  还是从 Authorization 请求头中获取

**Comment by lijiahangmax** [comment]
不用加 Authorization: Bearer {{.login.data.token}} 能自动获取到吗

**Comment by LinuxSuRen** [comment]
> 不用加 Authorization: Bearer {{.login.data.token}} 能自动获取到吗

我也有点困惑，每次会自动带上之前的 cookie，不知道为啥现在不需要加了。

**Comment by lijiahangmax** [comment]
好 那以后都先不加了.
