### ISSUE TITLE
目前是没有支持RDP协议吗？

### ISSUE THREAD

**Issue by 543069760** [dromara/orion-visor#32]
win RDP主机全部失败
![image](https://github.com/dromara/orion-visor/assets/127146064/b2addd82-606d-4fc3-8f84-36975dc328e5)
另外建议增加 代理 功能（可以通过代理缓解墙外机器卡顿、断联、联结失败的情况，可以参考：Next Terminal）
![image](https://github.com/dromara/orion-visor/assets/127146064/3c48dfb6-52c7-4af3-949a-6f5b51b61f3b)

**Comment by lijiahangmax** [comment]
RDP 现在是不支持的, proxy 后面会增加
