### ISSUE TITLE
如何配置服务器使用的ip

### ISSUE THREAD

**Issue by lihuan139** [dromara/orion-visor#38]
服务器有两个ip,如何让服务用我指定的ip
![微信截图_20240701143456](https://github.com/dromara/orion-visor/assets/116704206/2833b841-bd8e-4f3f-b057-4d122ec5d67d)

**Comment by lijiahangmax** [comment]
![image](https://github.com/dromara/orion-visor/assets/42642056/516cfad6-6817-45fd-8845-aca19693e5cd)

改成自己需要使用的
