### ISSUE TITLE
[BUG] The proxy request header cannot be correctly identified

### ISSUE THREAD

**Issue by MemoryShadow** [dromara/orion-visor#51]
**Describe the bug**
If a request is made to the orion-visor using either of the reverse proxy technologies, even with the `X-Real-IP` and `X-Forward-for` request headers set, the retained address is the address of the jumper and not the initiator's real address.

**To Reproduce**
1. Install orion-visor and nginx on the test machine
2. Create the following configuration for nginx:
```conf
location / {
    proxy_pass  http://127.0.0.1:1081;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
3. Check the IP address left in the "留痕地址" after logging into the service using the nginx address

**Expected behavior**
The program correctly recognizes the `X-Real-IP` and `X-Forwarded-For` headers, presenting the visitor's real IP address in the background "留痕地址"

**Comment by lijiahangmax** [comment]
获取的请求头为 x-real-ip 
![image](https://github.com/user-attachments/assets/14331d0f-894a-4899-8b4e-b59e0dc6bede)
我看demo 环境是没问题的呀
![image](https://github.com/user-attachments/assets/8898361e-cd99-4061-9c28-6f4e493e479b)

**Comment by MemoryShadow** [comment]
No, this is always the IP address of the jumper. You can try curl directly by using -H 'X-Real-IP: 1.1.1.1' to get the IP of the nearest layer

**Comment by MemoryShadow** [comment]
> 获取的请求头为 x-real-ip ![image](https://private-user-images.githubusercontent.com/42642056/356066772-14331d0f-894a-4899-8b4e-b59e0dc6bede.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODc2NjUsIm5iZiI6MTcyMzA4NzM2NSwicGF0aCI6Ii80MjY0MjA1Ni8zNTYwNjY3NzItMTQzMzFkMGYtODk0YS00ODk5LThiNGUtYjU5ZTBkYzZiZWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMzA2ZDIyY2MxZTczMzNmYWI2YzRlZjFiODg5ZDhkY2Y4ZGYzNzI4ZGExODlmNDBhN2YzNDVjMTVkNmMyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8MGXzFSe-xdAknXaE_SViyKgkffQu9rUAd61sk1z2WU) 我看demo 环境是没问题的呀 ![image](https://private-user-images.githubusercontent.com/42642056/356066957-8898361e-cd99-4061-9c28-6f4e493e479b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODc2NjUsIm5iZiI6MTcyMzA4NzM2NSwicGF0aCI6Ii80MjY0MjA1Ni8zNTYwNjY5NTctODg5ODM2MWUtY2Q5OS00MDYxLTljMjgtNmY0ZTQ5M2U0NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzMjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjE4ZDJiOTM3OTBjY2Q5OTU2YTIwMzVmZDhhMDRlODZjMGYzMzAwYWJhNWU0MGExY2IxOGJmYzdjNWI5YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C_tHGS7jBIvPJ4bCmv_vOXZmjxbjSp22ylhWpI_CG-Y)

No, this is always the IP address of the jumper. You can try using curl directly by using -H 'X-Real-IP: 1.1.1.1'. The IP of the nearest machine is always obtained

**Comment by lijiahangmax** [comment]
![image](https://github.com/user-attachments/assets/68b32c41-fc5f-464f-a3c4-dc96ab7b49c7)
![image](https://github.com/user-attachments/assets/5c024379-2e71-4bbe-853e-e52c68ba8fd3)

**Comment by lijiahangmax** [comment]
![image](https://github.com/user-attachments/assets/8c6f710d-d786-4fc3-a63f-90ce5092812c)
![image](https://github.com/user-attachments/assets/cb549ffc-9ad0-4bd6-8357-2c6da2ad98bb)

**Comment by MemoryShadow** [comment]
> ![image](https://private-user-images.githubusercontent.com/42642056/356078579-8c6f710d-d786-4fc3-a63f-90ce5092812c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI2MTIsIm5iZiI6MTcyMzA5MjMxMiwicGF0aCI6Ii80MjY0MjA1Ni8zNTYwNzg1NzktOGM2ZjcxMGQtZDc4Ni00ZmMzLWE2M2YtOTBjZTUwOTI4MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YTVmN2JkNTU4NTdiMGQxMTFmYWFiNzE4OTJhYWMxNDFhMTA2NGIyZmI0MTVjNjAzMDIwMjVkZGMwYjk2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._IoHuUjxgubmm7X-Nd3K_XO9Vnl9RSyJzv4PkWu7YL0) ![image](https://private-user-images.githubusercontent.com/42642056/356080127-cb549ffc-9ad0-4bd6-8357-2c6da2ad98bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTI2MTIsIm5iZiI6MTcyMzA5MjMxMiwicGF0aCI6Ii80MjY0MjA1Ni8zNTYwODAxMjctY2I1NDlmZmMtOWFkMC00YmQ2LTgzNTctMmM2ZGEyYWQ5OGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0M2NmNTNjNmNmMmM4ODE3ZWQwMDFjMTc1ZTIxNmRiNTU1NWQ1Zjc2ODNkMGViZGVmMDZhNjk1MDQ1ZjVkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJmX74uXT0-AIGcgjLjf1bpqiKbQCQVAP9MHoQuEb_4)

Note here that the IP of the mark should be 62.123.44.14, but it is the jumper 116.62.194.246. In a reverse proxy environment, the real IP address of the visitor can never be obtained

**Comment by lijiahangmax** [comment]
访问的ip不就是 116.62.194.246 吗, 不允许手动指定 X-real-ip, 防止ip伪造, 如果想通过请求头获取的话需要自行修改 ipUtils 的逻辑
