### ISSUE TITLE
忘记admin的密码怎么办

### ISSUE THREAD

**Issue by 1447443432** [dromara/orion-visor#68]
修改过admin的密码，然后忘记了，如何重置或者找回呢

**Comment by 1447443432** [comment]
![image](https://github.com/user-attachments/assets/495c85d1-7323-4b8c-9344-be62f1a9ce98)
现在这个如何解呀，急急~

**Comment by lijiahangmax** [comment]
1. 连接 mysql 找到 system_user 表, 找到数据. 将密码改为 c3284d0f94606de1fd2af172aba15bf3 (admin)
2. 连接 redis 找到 user:login-failed:admin 删除

**Comment by 1447443432** [comment]
嗯嗯，谢谢大佬
