### ISSUE TITLE
创建主机 功能禁用后，依然可以创建主机

### ISSUE THREAD

**Issue by PungYoung** [dromara/orion-visor#72]
在菜单管理中禁用主机管理后
![image](https://github.com/user-attachments/assets/ba5cf4f6-3458-47ff-b3ac-2c1235bcf11c)

资产管理 - 主机管理 - 创建主机依然可用
![image](https://github.com/user-attachments/assets/274b8c57-2e18-4d51-8bfa-aa70f703c3f2)

**Comment by lijiahangmax** [comment]
创建时会报错吗

**Comment by PungYoung** [comment]
> 创建时会报错吗

不会，直接创建成功

**Comment by lijiahangmax** [comment]
我检查了下代码逻辑, 是管理员用户逻辑有问题, 下个版本修复一下

**Comment by lijiahangmax** [comment]
普通用户应该没有这个问题  你可以试试看

**Comment by PungYoung** [comment]
> 普通用户应该没有这个问题 你可以试试看

好的
