### ISSUE TITLE
可否添加ssh代理方式登陆？

### ISSUE THREAD

**Issue by 9uest** [dromara/orion-visor#78]
比如说我使用frp，实现内网穿透，因为我用的端口复用，想连接主机使用
连接方法为： a.xxx.com 为内网主机
ssh -o 'proxycommand socat - PROXY:公网:a.xxx.com:22,proxyport=公网端口' a.xxx.com

这种方式支持添加么？

**Comment by lijiahangmax** [comment]
其实底层是支持的, 时间不够没实现, sessionStore.proxy()

**Comment by Airren** [comment]
附议，
